#ifndef ANET_INCLUDE_ANET_BASE_CONCAT_HPP_
#define ANET_INCLUDE_ANET_BASE_CONCAT_HPP_

#define __ANET_CONCAT(a, b) a##b
#define ANET_CONCAT(a, b) __ANET_CONCAT(a, b)

#endif //ANET_INCLUDE_ANET_BASE_CONCAT_HPP_
